global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    env: production

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: node-exporter
    static_configs:
      - targets: ['localhost:9100']  # node-exporter en host network

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  # Active ce bloc seulement si tu ajoutes nginx-exporter
  - job_name: nginx
    static_configs:
      - targets: ['nginx-exporter:9113']
