name: Hello World CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PWD }}
          
      - name: Build Docker image
        run: docker build -t pucepanique3/devops-tp3 .

      - name: Tag Docker image
        run: docker tag pucepanique3/devops-tp3 ${{ secrets.DOCKER_NAME }}/pucepanique3/devops-tp3:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_NAME }}/pucepanique3/devops-tp3:latest
