name: Hello World CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PWD }}
          
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_NAME }}/devops-tp3 .

      - name: Tag Docker image
        run: docker tag ${{ secrets.DOCKER_NAME }}/devops-tp3 ${{ secrets.DOCKER_NAME }}/${{ secrets.DOCKER_NAME }}/devops-tp3:latest

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_NAME }}/${{ secrets.DOCKER_NAME }}/devops-tp3:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy via SSH with password
        run: |
          sshpass -p "${{ secrets.VPS_PWD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
          "docker stop ${{ secrets.DOCKER_NAME }}/devops-tp3 || true &&
          docker rm ${{ secrets.DOCKER_NAME }}/devops-tp3 || true &&
          docker pull ${{ secrets.DOCKER_NAME }}/devops-tp3:latest &&
          docker run -d --name ${{ secrets.DOCKER_NAME }}/devops-tp3 -p 8080:8080 ${{ secrets.DOCKER_NAME }}/${{ secrets.DOCKER_NAME }}/devops-tp3:latest"
