name: Hello World CI

on:
  push:
    branches:
      - Prod

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_NAME }}/devops-tp3:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_NAME }}/devops-tp3:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo docker stop devops-tp3 || true
            sudo docker rm devops-tp3 || true
            sudo docker pull ${{ secrets.DOCKER_NAME }}/devops-tp3:latest
            sudo docker run -d --name devops-tp3 -p 80:80 ${{ secrets.DOCKER_NAME }}/devops-tp3:latest

